apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bd50t4uxy-nodejs
  janus-idp.io/tekton: bd50t4uxy-nodejs
  backstage.io/kubernetes-id: bd50t4uxy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bd50t4uxy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
